// SET ENVIRONMENT VARIABLES BEFORE MODULES ARE LOADED
process.env.ISTACK_INFO_SERVICE_BASE_URL = 'http://localhost:3001';
process.env.ISTACK_INFO_SERVICE_API_KEY = '_THE_FAKE_INFO_SERVICE_KEY_';
process.env.ANTHROPIC_API_KEY = '_FAKE_ANTHROPIC_API_KEY_FOR_JEST';
process.env.OPENAI_API_KEY = '_FAKE_OPENAI_KEY_';
process.env.ISTACK_BUDDY_INTERNAL_JWT_SECRET = 'istack-buddy-secret-key-2024';
process.env.NODE_ENV = 'test';
process.env.LOG_LEVEL = 'error';
